{% set version = "1.3.2" %}

package:
  name: apptainer
  version: {{ version }}

source:
  - folder: src/github.com/apptainer/apptainer
    url: https://github.com/apptainer/apptainer/releases/download/v{{ version }}/apptainer-{{ version }}.tar.gz
    sha256: 483910727e1a15843b93d9f2db1fc87e27804de9c74da13cc32cd4bd0d35e079
    patches:
      - patches/0003-Use-external-CNI.patch

build:
  number: 0
  skip: true  # [not linux]
  # The binary is made runtime relocatable using the included patch
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cgo') }}
    - make
    - pkg-config
    - go-dep
    - sed
  host:
    - libuuid  # [linux]
    - libarchive
    - libseccomp  # [linux]
    - openssl
  run:
    # CNI version from singularity/Gopkg.lock
    - cni-plugins >=0.7.4  # [linux]
    - squashfs-tools  # [linux]
  run_constrained:
    - singularity ==9999999999

test:
  commands:
    - apptainer --help
    - singularity --help
    # disable these tests to ensure verbosity problem isn't from here (ngam)
    - apptainer --version

    # Ensure the version is set correctly
    - apptainer --version | grep {{ version }}
    - singularity --version | grep {{ version }}

    # Ensure we are using conda's CNI
    - test ! -d $PREFIX/libexec/apptainer/cni
    - test -d $PREFIX/lib/cni

    - test ! -d $PREFIX/etc/apptainer/network
    - test -f $PREFIX/etc/cni/net.d/00_bridge.conflist

about:
  home: https://apptainer.org/
  license: BSD-3-Clause
  license_file: src/github.com/apptainer/apptainer/LICENSE.md
  summary: 'Apptainer: Application containers for Linux'
  description: |
    Apptainer/Singularity is the most widely used container system for HPC. It
    is designed to execute applications at bare-metal performance while being
    secure, portable, and 100% reproducible. Apptainer is an open-source
    project with a friendly community of developers and users. The user base
    continues to expand, with Apptainer/Singularity now used across industry
    and academia in many areas of work.
  dev_url: https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md
  doc_url: https://apptainer.org/docs/

extra:
  recipe-maintainers:
    - mbargull
    - chrisburr
    - multimeric
